api_platform:
  title: USER-API
  version: 1.0.0
  show_webby: false
  mapping:
    paths: [ '%kernel.project_dir%/src/ApiResource' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
  swagger:
    versions: [ 3 ]
  enable_docs: false

when@dev:
  api_platform:
    enable_docs: true